version: "3.8"

services:
  web:
    depends_on: 
      - api
    build: ./frontend
    ports:
      - 5173:5173
    environment:
      VITE_API_URL: http://localhost:8000
    develop:
      watch:
        # it'll watch for changes in package.json and package-lock.json and rebuild the container if there are any changes
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild
        # it'll watch for changes in the frontend directory and sync the changes with the container real time
        - path: ./frontend
          target: /app
          action: sync

  # define the api service/container
  api: 
    depends_on: 
      - db
    build: ./backend
    ports: 
      - 8000:8000
    environment: 
      DB_URL: mongodb://db/anime
    develop:
      watch:
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend/package-lock.json
          action: rebuild
        - path: ./backend
          target: /app
          action: sync

  # define the db service
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - anime:/data/db

# define the volumes to be used by the services
volumes:
  anime: